- id: 100
  title: "Welcome to Life & Nature Acupuncture and Holistic Medicine"
  id_no: 10000
  category: 0
  name: 'Home'
  link: '' 
  active: true 
  note: 
  meta: 'Acupuncture, Medical CalOptima, Natural Skin care, Natural medicine, non invasive, holistic medicine natural pain killer, chronic pain, severe pain, best acupuncture, anaheim, orange county, Personal injury acupuncture'

- id: 200 
  title: "Acupuncture, Physical Therapy, Moxa, Gua sha, Guasha, Facial Acupuncture, Electric Acupuncture, Herb, Detox, Weight Loss, Pain management"
  id_no: 20000
  category: 0
  name: 'Services'
  link: '' 
  active: true
  note: 
  meta: "service meta test"

- id: 201 
  id_no: 20000
  title: "Acupuncture, Physical Therapy, Moxa, Gua sha, Guasha, Facial Acupuncture, Electric Acupuncture, Herb, Detox, Weight Loss, Pain management"
  category: 'Services'
  name: 'Acupuncture'
  link: '' 
  active: true
  note: 
  meta: 'Acupuncture, Medical CalOptima, Natural Skin care, Natural medicine, non invasive, holistic medicine natural pain killer, chronic pain, severe pain, best acupuncture, anaheim, orange county, Personal injury acupuncture'

- id: 202 
  id_no: 20000
  title: "Acupuncture, Physical Therapy, Moxa, Gua sha, Guasha, Facial Acupuncture, Electric Acupuncture, Herb, Detox, Weight Loss, Pain management"
  category: 'Services'
  name: 'Holistic Therapy'
  link: '' 
  active: true
  AD1: 'All in One Holistic Therapy'
  AD2:  'Chiropractic, Massage, Physical Therapy'
  note: 
  meta: 'Acupuncture, Medical CalOptima, Natural Skin care, Natural medicine, non invasive, holistic medicine natural pain killer, chronic pain, severe pain, best acupuncture, anaheim, orange county, Personal injury acupuncture'
  
- id: 203 
  id_no: 20000
  title: "Detox, Weight Loss, Weight management, Natural Herbal Detox, Liver Cleansing, Kidney Cleansing, Anti Inflamation"
  category: 'Services'
  name: 'Detox & Blance'
  link: '' 
  active: true 
  note: 
  meta: 'Acupuncture, Medical CalOptima, Natural Skin care, Natural medicine, non invasive, holistic medicine natural pain killer, chronic pain, severe pain, best acupuncture, anaheim, orange county, Personal injury acupuncture'


- id: 204 
  id_no: 20000
  category: 'Services'
  name: ''
  link: '' 
  active: true 
  note: 
  meta: 'Acupuncture, Medical CalOptima, Natural Skin care, Natural medicine, non invasive, holistic medicine natural pain killer, chronic pain, severe pain, best acupuncture, anaheim, orange county, Personal injury acupuncture'

- id: 205 
  id_no: 20000
  category: 'Services'
  title: "Acne, Weight Loss, Weight management, Natural Herbal Detox, Liver Cleansing, Kidney Cleansing, Anti Inflamation"
  name: 'Facial Care'
  link: '' 
  active: true 
  note: 
  meta: 'Acupuncture, Medical CalOptima, Natural Skin care, Natural medicine, non invasive, holistic medicine natural pain killer, chronic pain, severe pain, best acupuncture, anaheim, orange county, Personal injury acupuncture'

- id: 206 
  id_no: 20000
  category: 'Services'
  title: "Natural Cancer Treatment, Immune Therapy for Cancer, Cancer Pain, Treatment for chemotherapy side effects, Treatment for Radiation Side effects, Support recovery from cancer surgery"
  name: 'Oncology Supportive Care'
  link: '' 
  active: true 
  note: 
  meta: 'Acupuncture, Medical CalOptima, Natural Skin care, Natural medicine, non invasive, holistic medicine natural pain killer, chronic pain, severe pain, best acupuncture, anaheim, orange county, Personal injury acupuncture'

- id: 207 
  id_no: 20000
  category: 'Services'
  title: "Functional medicine,Nutrition counseling, vitamin therapy, Healthy diet, Herbal Medicine, Natural supplements, homeopathy"
  name: 'Homeopathy & Natural Supplements'
  link: '' 
  active: true 
  note: 
  meta: 'Acupuncture, Medical CalOptima, Natural Skin care, Natural medicine, non invasive, holistic medicine natural pain killer, chronic pain, severe pain, best acupuncture, anaheim, orange county, Personal injury acupuncture'

- id: 208 
  id_no: 20000
  category: 'Services'
  title: 'Services'
  name: 'Health Test'
  link: '' 
  active: true 
  note: 
  meta: 'Acupuncture, Medical CalOptima, Natural Skin care, Natural medicine, non invasive, holistic medicine natural pain killer, chronic pain, severe pain, best acupuncture, anaheim, orange county, Personal injury acupuncture'





- id: 300 
  id_no: 10000
  category: 'Conditions'
  name: ''
  link: '' 
  active: true
  note: 

- id: 301 
  id_no: 10000
  category: 'Conditions'
  name: 'Chronic & Severe Pain'
  link: '' 
  active: true
  note:
  youtube: 'https://www.youtube.com/embed/h7g5N3qiVeg?feature=oembed=0=0=0'
  meta: 'Acupuncture, Medical CalOptima, Natural Skin care, Natural medicine, non invasive, holistic medicine natural pain killer, chronic pain, severe pain, best acupuncture, anaheim, orange county, Personal injury acupuncture'

- id: 302 
  id_no: 10000
  category: 'Conditions'
  name: 'Neurological Disorders'
  link: '' 
  active: true
  note:
  meta: 'Acupuncture, Medical CalOptima, Natural Skin care, Natural medicine, non invasive, holistic medicine natural pain killer, chronic pain, severe pain, best acupuncture, anaheim, orange county, Personal injury acupuncture'

- id: 303 
  id_no: 10000
  category: 'Conditions'
  name: 'Mood & Emotional Disorders'
  link: '' 
  active: true
  note:
  meta: 'Acupuncture, Medical CalOptima, Natural Skin care, Natural medicine, non invasive, holistic medicine natural pain killer, chronic pain, severe pain, best acupuncture, anaheim, orange county, Personal injury acupuncture'

- id: 304 
  id_no: 10000
  category: 'Conditions'
  name: 'Autoimmune Disorders'
  link: '' 
  active: true
  note:
  meta: 'Acupuncture, Medical CalOptima, Natural Skin care, Natural medicine, non invasive, holistic medicine natural pain killer, chronic pain, severe pain, best acupuncture, anaheim, orange county, Personal injury acupuncture'

- id: 305 
  id_no: 10000
  category: 'Conditions'
  name: 'Digestsive Disorders'
  link: '' 
  active: true
  note:
  meta: 'Acupuncture, Medical CalOptima, Natural Skin care, Natural medicine, non invasive, holistic medicine natural pain killer, chronic pain, severe pain, best acupuncture, anaheim, orange county, Personal injury acupuncture'

- id: 306 
  id_no: 10000
  category: 'Conditions'
  name: 'Oncology Supportive Care'
  link: '' 
  active: true
  note:
  meta: 'Acupuncture, Medical CalOptima, Natural Skin care, Natural medicine, non invasive, holistic medicine natural pain killer, chronic pain, severe pain, best acupuncture, anaheim, orange county, Personal injury acupuncture'

- id: 307 
  id_no: 10000
  category: 'Conditions'
  name: 'Women''s Health'
  link: '' 
  active: true
  note:
  meta: 'Acupuncture, Medical CalOptima, Natural Skin care, Natural medicine, non invasive, holistic medicine natural pain killer, chronic pain, severe pain, best acupuncture, anaheim, orange county, Personal injury acupuncture'

- id: 308 
  id_no: 10000
  category: 'Conditions'
  name: 'Children''s Health'
  link: '' 
  active: true
  note:
  meta: 'Acupuncture, Medical CalOptima, Natural Skin care, Natural medicine, non invasive, holistic medicine natural pain killer, chronic pain, severe pain, best acupuncture, anaheim, orange county, Personal injury acupuncture'

- id: 309 
  id_no: 10000
  category: 'Conditions'
  name: 'Skin Conditions'
  link: '' 
  active: true
  note:
  meta: 'Acupuncture, Medical CalOptima, Natural Skin care, Natural medicine, non invasive, holistic medicine natural pain killer, chronic pain, severe pain, best acupuncture, anaheim, orange county, Personal injury acupuncture'

- id: 310
  id_no: 10000
  category: 'Conditions'
  name: 'Men''s Health'
  link: '' 
  active: true
  note:
  meta: 'Acupuncture, Medical CalOptima, Natural Skin care, Natural medicine, non invasive, holistic medicine natural pain killer, chronic pain, severe pain, best acupuncture, anaheim, orange county, Personal injury acupuncture'

- id: 311
  id_no: 10000
  category: 'Conditions'
  name: 'Addictions'
  link: '' 
  active: true
  note:
  meta: 'Acupuncture, Medical CalOptima, Natural Skin care, Natural medicine, non invasive, holistic medicine natural pain killer, chronic pain, severe pain, best acupuncture, anaheim, orange county, Personal injury acupuncture'

- id: 312
  id_no: 10000
  category: 'Conditions'
  name: 'Digestive Disorders'
  link: '' 
  active: true
  note:
  meta: 'Acupuncture, Medical CalOptima, Natural Skin care, Natural medicine, non invasive, holistic medicine natural pain killer, chronic pain, severe pain, best acupuncture, anaheim, orange county, Personal injury acupuncture'


- id: 400 
  id_no: 10000
  category: ''
  name: 'Blogs'
  link: '' 
  active: true
  note: 
  meta: 'Acupuncture, Medical CalOptima, Natural Skin care, Natural medicine, non invasive, holistic medicine natural pain killer, chronic pain, severe pain, best acupuncture, anaheim, orange county, Personal injury acupuncture'

- id: 500 
  id_no: 10000
  category: ''
  name: 'FAQ'
  link: '' 
  active: false
  note: 
  meta: 'Acupuncture, Medical CalOptima, Natural Skin care, Natural medicine, non invasive, holistic medicine natural pain killer, chronic pain, severe pain, best acupuncture, anaheim, orange county, Personal injury acupuncture'

- id: 600 
  id_no: 10000
  category: ''
  name: 'Appointments & Visits'
  link: '' 
  active: false
  note: 
  meta: 'Acupuncture, Medical CalOptima, Natural Skin care, Natural medicine, non invasive, holistic medicine natural pain killer, chronic pain, severe pain, best acupuncture, anaheim, orange county, Personal injury acupuncture'

- id: 601 
  id_no: 10000
  category: 'Appointments & Visits'
  name: 'Appointments' 
  link: '' 
  active: false
  note: 
  meta: 'Acupuncture, Medical CalOptima, Natural Skin care, Natural medicine, non invasive, holistic medicine natural pain killer, chronic pain, severe pain, best acupuncture, anaheim, orange county, Personal injury acupuncture'

- id: 602 
  id_no: 10000
  category: 'Appointments & Visits'
  name: 'Visits'
  link: '' 
  active: false
  note: 
  meta: 'Acupuncture, Medical CalOptima, Natural Skin care, Natural medicine, non invasive, holistic medicine natural pain killer, chronic pain, severe pain, best acupuncture, anaheim, orange county, Personal injury acupuncture'

- id: 603 
  id_no: 10000
  category: 'Appointments & Visits'
  name: 'Visit'
  link: '' 
  active: false
  note: 
  meta: 'Acupuncture, Medical CalOptima, Natural Skin care, Natural medicine, non invasive, holistic medicine natural pain killer, chronic pain, severe pain, best acupuncture, anaheim, orange county, Personal injury acupuncture'

- id: 700 
  id_no: 10000
  category: 0 
  name: 'About us'
  link: '' 
  active: true
  note: 
  meta: 'Acupuncture, Medical CalOptima, Natural Skin care, Natural medicine, non invasive, holistic medicine natural pain killer, chronic pain, severe pain, best acupuncture, anaheim, orange county, Personal injury acupuncture'

- id: 702 
  id_no: 10000
  category: 'About us' 
  name: 'Meet us'
  link: '' 
  active: true
  note: 
  meta: 'Acupuncture, Medical CalOptima, Natural Skin care, Natural medicine, non invasive, holistic medicine natural pain killer, chronic pain, severe pain, best acupuncture, anaheim, orange county, Personal injury acupuncture'

- id: 703 
  id_no: 10000
  category: 'About us' 
  name: 'Case Studies & Testimonials'
  link: '' 
  active: true
  note: 
  meta: 'Acupuncture, Medical CalOptima, Natural Skin care, Natural medicine, non invasive, holistic medicine natural pain killer, chronic pain, severe pain, best acupuncture, anaheim, orange county, Personal injury acupuncture'

- id: 704 
  id_no: 10000
  category: 'About us' 
  name: 'Galleries'
  link: '' 
  active: true
  note: 
  meta: 'Acupuncture, Medical CalOptima, Natural Skin care, Natural medicine, non invasive, holistic medicine natural pain killer, chronic pain, severe pain, best acupuncture, anaheim, orange county, Personal injury acupuncture'

- id: 701 
  id_no: 10000
  category: 'About us' 
  name: 'Business Hours & Location'
  link: '' 
  active: true
  note: 
  meta: 'Acupuncture, Medical CalOptima, Natural Skin care, Natural medicine, non invasive, holistic medicine natural pain killer, chronic pain, severe pain, best acupuncture, anaheim, orange county, Personal injury acupuncture'

- id: 800 
  id_no: 10000
  category: 
  name: 'Price & Insurance'
  link: '' 
  active: false
  note: 
  meta: 'Acupuncture, Medical CalOptima, Natural Skin care, Natural medicine, non invasive, holistic medicine natural pain killer, chronic pain, severe pain, best acupuncture, anaheim, orange county, Personal injury acupuncture'


- id: 1000
  id_no: 10000
  category: 'Admin' 
  name: 'Users'
  link: '' 
  active: true 
  note: 
  meta: 
  meta: 'Acupuncture, Medical CalOptima, Natural Skin care, Natural medicine, non invasive, holistic medicine natural pain killer, chronic pain, severe pain, best acupuncture, anaheim, orange county, Personal injury acupuncture'

- id: 000
  id_no: 30000
  category: 'Admin'
  name: 'Blogs'
  link: '' 
  active: false
  note: 
  meta: 'Acupuncture, Medical CalOptima, Natural Skin care, Natural medicine, non invasive, holistic medicine natural pain killer, chronic pain, severe pain, best acupuncture, anaheim, orange county, Personal injury acupuncture'

- id: 1002
  id_no: 30000
  category: 'Admin'
  name: 'Products'
  link: '' 
  active: false
  note: 
  meta: 'Acupuncture, Medical CalOptima, Natural Skin care, Natural medicine, non invasive, holistic medicine natural pain killer, chronic pain, severe pain, best acupuncture, anaheim, orange county, Personal injury acupuncture'

