- id: 1
  menu_id: 301 
  active: true
  title: 'Totally worth it! '
  reviewer: 'Jousha S.   Hayward, CA'
  review_date: '8/14/2018'
  review: 'I''ve been going to Soo Jin for for a couple months now to help alleviate back pain (which has been good!) but I didn''t expect acupuncture to help improve my overall body health too!<br>br> Totally worth it! <br><br>She explains the process well as she works on you and is gentle and kind too. I''d recommend this place to my friends and family.'
  youtube: 'https://www.youtube.com/embed/h7g5N3qiVeg?feature=oembed=0=0=0'
  picture: "15.jpg"

- id: 2 
  menu_id: 206 
  active: true 
  title : 'Acupuncture kept me from getting nausea and keeping my energy up'
  reviewer: 'Steve U.   Santa Ana CA,    '
  review : 'Soojin has been treating me for more then one year, when I started my chemo and radiation therapy for my cancer,  I fell that the acupuncture kept me from getting nausea and keeping my energy up. Soojin is a vary good acupuncturist she always takes time to ask how you are, is there any changes in your health. She will recommend some treatments and explain what she''s going to do. Soojin always make me feel vary cared for and I would recommend her to anyone, I would like to thank the Lord for sending her to me.
    <br>PS, She will care for you like you are family. Thank you
    Your brother in Christ, Steve.   '
  review_date : '10/10/2018'
  picture: "11.jpg"
  youtube: 'https://www.youtube.com/embed/NYyN8Q5ew3E?feature=oembed=0=0=0'
  note: 

- id: 3 
  menu_id: 304 
  active: true 
  title : 'Acupuncture is Amazing and it really does work!'
  reviewer: 'Kimberly B.   Tustin, CA'
  review : 'I am very thankful to have been referred to Life & Nature Acupuncture. I was in a lot of pain and had chronic inflammation in my joints and bed bound for many years. This kind of pain I was in every morning, made me frustrated and I knew I needed real help. I have been convinced that Acupuncture is Amazing and it really does work. I still have a long way to go in my healing process but the help I am receiving is priceless. If you''re in chronic pain of any kind, come and experience getting real help from an expert.'
  review_date : '10/30/2018'
  picture: 'testimony-kim-b.jpg'
  youtube: 
  note: '34 year-old-female with Postpartum Rheumatoid Arthritis
    with knee and elbow joints crooked<br><br>
    Treatment Methods: Acupuncture, Detoxification, Personalized Diet Plan,
    Natural Supplements'

    

