- id: 1
  menu_id: 301 
  active: true
  title: 'Totally worth it! '
  reviewer: 'Jousha S.   Hayward, CA'
  review_date: '8/14/2018'
  review: 'I''ve been going to Soo Jin for for a couple months now to help alleviate back pain (which has been good!) but I didn''t expect acupuncture to help improve my overall body health too!<br>br> Totally worth it! <br><br>She explains the process well as she works on you and is gentle and kind too. I''d recommend this place to my friends and family.'
  youtubu: ''

- id: 2 
  menu_id: 206 
  active: true 
  title : 'Acupuncture kept me from getting nausea and keeping my energy up'
  reviewer: 'Steve U.   Santa Ana CA,    '
  review : 'Soojin has been treating me for more then one year, when I started my chemo and radiation therapy for my cancer,  I fell that the acupuncture kept me from getting nausea and keeping my energy up. Soojin is a vary good acupuncturist she always takes time to ask how you are, is there any changes in your health. She will recommend some treatments and explain what she''s going to do. Soojin always make me feel vary cared for and I would recommend her to anyone, I would like to thank the Lord for sending her to me.
    <br>PS, She will care for you like you are family. Thank you
    Your brother in Christ, Steve.   '
  review_date : '10/10/2018'
  picture: ''
  youtube: 'https://www.youtube.com/embed/NYyN8Q5ew3E?feature=oembed=0=0=0'
  note: 

